package com.nxdcms.entity;
// Generated 2016-10-14 10:20:41 by Hibernate Tools 3.2.2.GA

/**
 * Administrator generated by hbm2java
 */
public class Administrator implements java.io.Serializable {

	private String administratorId;
	private String administratorPassword;
	private String administratorName;
	private String administratorCollege;
	private String administratorEmail;
	private String administratorPhnoe;
	private byte addInfoPriv;
	private byte deleteInfoPriv;
	private byte modifyInfoPriv;
	private byte addStuPriv;
	private byte deleteStuPriv;
	private byte modifyStuPriv;
	private byte addAdmPriv;
	private byte modifyAdmPriv;
	private byte deleteAdmPriv;

	public Administrator() {
	}

	public Administrator(String administratorId, String administratorPassword, String administratorName,
			String administratorCollege, String administratorEmail) {
		this.administratorId = administratorId;
		this.administratorPassword = administratorPassword;
		this.administratorName = administratorName;
		this.administratorCollege = administratorCollege;
		this.administratorEmail = administratorEmail;
	}

	public Administrator(String administratorId, String administratorPassword, String administratorName,
			String administratorCollege, String administratorEmail, String administratorPhnoe) {
		this.administratorId = administratorId;
		this.administratorPassword = administratorPassword;
		this.administratorName = administratorName;
		this.administratorCollege = administratorCollege;
		this.administratorEmail = administratorEmail;
		this.administratorPhnoe = administratorPhnoe;
	}

	public String getAdministratorId() {
		return this.administratorId;
	}

	public void setAdministratorId(String administratorId) {
		this.administratorId = administratorId;
	}

	public String getAdministratorPassword() {
		return this.administratorPassword;
	}

	public void setAdministratorPassword(String administratorPassword) {
		this.administratorPassword = administratorPassword;
	}

	public String getAdministratorName() {
		return this.administratorName;
	}

	public void setAdministratorName(String administratorName) {
		this.administratorName = administratorName;
	}

	public String getAdministratorCollege() {
		return this.administratorCollege;
	}

	public void setAdministratorCollege(String administratorCollege) {
		this.administratorCollege = administratorCollege;
	}

	public String getAdministratorEmail() {
		return this.administratorEmail;
	}

	public void setAdministratorEmail(String administratorEmail) {
		this.administratorEmail = administratorEmail;
	}

	public String getAdministratorPhnoe() {
		return this.administratorPhnoe;
	}

	public void setAdministratorPhnoe(String administratorPhnoe) {
		this.administratorPhnoe = administratorPhnoe;
	}

	public byte getAddInfoPriv() {
		return addInfoPriv;
	}

	public void setAddInfoPriv(byte addInfoPriv) {
		this.addInfoPriv = addInfoPriv;
	}

	public byte getDeleteInfoPriv() {
		return deleteInfoPriv;
	}

	public void setDeleteInfoPriv(byte deleteInfoPriv) {
		this.deleteInfoPriv = deleteInfoPriv;
	}

	public byte getModifyInfoPriv() {
		return modifyInfoPriv;
	}

	public void setModifyInfoPriv(byte modifyInfoPriv) {
		this.modifyInfoPriv = modifyInfoPriv;
	}

	public byte getAddStuPriv() {
		return addStuPriv;
	}

	public void setAddStuPriv(byte addStuPriv) {
		this.addStuPriv = addStuPriv;
	}

	public byte getDeleteStuPriv() {
		return deleteStuPriv;
	}

	public void setDeleteStuPriv(byte deleteStuPriv) {
		this.deleteStuPriv = deleteStuPriv;
	}

	public byte getModifyStuPriv() {
		return modifyStuPriv;
	}

	public void setModifyStuPriv(byte modifyStuPriv) {
		this.modifyStuPriv = modifyStuPriv;
	}

	public byte getAddAdmPriv() {
		return addAdmPriv;
	}

	public void setAddAdmPriv(byte addAdmPriv) {
		this.addAdmPriv = addAdmPriv;
	}

	public byte getModifyAdmPriv() {
		return modifyAdmPriv;
	}

	public void setModifyAdmPriv(byte modifyAdmPriv) {
		this.modifyAdmPriv = modifyAdmPriv;
	}

	public byte getDeleteAdmPriv() {
		return deleteAdmPriv;
	}

	public void setDeleteAdmPriv(byte deleteAdmPriv) {
		this.deleteAdmPriv = deleteAdmPriv;
	}

	

}
